files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%locale_with_underscore%/strings.xml
  - source: /fastlane/metadata/android/en-US/full_description.txt
    translation: /fastlane/metadata/android/%locale_with_underscore%/full_description.txt
  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/metadata/android/%locale_with_underscore%/short_description.txt
  - source: /fastlane/metadata/android/en-US/title.txt
    translation: /fastlane/metadata/android/%locale_with_underscore%/title.txt
