name: Android CI

on:
  push:
    branches:
      - 'develop'
      - 'release/*'

jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: bash ./gradlew test

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Update Run Number in properties
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: RUN_NUMBER
          value: ${{ github.run_number }}

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Remove old debug keystore
        run: rm /home/runner/.android/debug.keystore

      - name: Generating debug keystore
        run: bash keytool -genkey -dname "cn=Seth Schroeder, ou=UNKNOWN, o=UNKNOWN, l=UNKNOWN, st=UNKNOWN, c=UNKNOWN" -keystore /home/runner/.android/debug.keystore -storepass ${{ secrets.CI_KEY_STORE_PASSWORD }} -alias ${{ secrets.CI_ALIAS }} -keyalg RSA -keysize 4096 -validity 10000 -v

      - name: Generate signing key
        run: bash keytool -list -v -keystore /home/runner/.android/debug.keystore -alias ${{ secrets.CI_ALIAS }} -storepass ${{ secrets.CI_KEY_STORE_PASSWORD }} -keypass ${{ secrets.CI_KEY_PASSWORD }}

      - name: Build debug APK
        run: bash ./gradlew assembleCi --stacktrace

      - name: set apk name env
        run: echo ::set-env name=APK_NAME::$(basename app/build/outputs/apk/ci/*.apk .apk)

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/ci/${{ env.APK_NAME }}.apk

      - name: Upload to Discord
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: app/build/outputs/apk/ci/${{ env.APK_NAME }}.apk
