name: Android CI

on:
  push:
    branches:
      - 'develop'
      - 'release/*'

jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: bash ./gradlew test

  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Update Run Number in properties
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: RUN_NUMBER
          value: ${{ github.run_number }}

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug APK
        run: bash ./gradlew assembleCi --stacktrace
        
      - name: Sign build
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/ci
          signingKeyBase64: ${{ secrets.CI_SIGNING_KEY }}
          alias: ${{ secrets.CI_ALIAS }}
          keyStorePassword: ${{ secrets.CI_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.CI_KEY_PASSWORD }}

      - name: set apk name env
        run: echo ::set-env name=APK_NAME::$(basename app/build/outputs/apk/ci/*.apk .apk)

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APK_NAME }}
          path: app/build/outputs/apk/ci/${{ env.APK_NAME }}.apk

      - name: Upload to Discord
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: app/build/outputs/apk/ci/${{ env.APK_NAME }}.apk
